# Site settings
title: "Project: Get Hired as a Project Manager"
email: zwa004@gmail.com
description: >- 
  This is your portfolio site where you showcase your projects, experiences, and skills.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zwa004.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Optional settings
author: Your Name
twitter_username: yourusername  # Optional
github_username:  zwa004  # Optional

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

